SELECT 
    T.QUERY_ID,
    T.QUERY_TEXT,
    T.EXECUTION_STATUS,
    T.START_TIME,
    DECODE(T.END_TIME,'1970-01-01 01:00:00.000'::TIMESTAMP,NULL,T.END_TIME) AS END_TIME,
    T.COMPILATION_TIME,
    T.EXECUTION_TIME,
    T.TOTAL_ELAPSED_TIME,
    -- For RUNNING queries, calculate elapsed time manually
    CASE 
        WHEN T.EXECUTION_STATUS = 'RUNNING' THEN 
            DATEDIFF(SECOND, T.START_TIME, CURRENT_TIMESTAMP())
        ELSE 
            T.TOTAL_ELAPSED_TIME / 1000 
    END as DURATION_SECONDS,
    T.TOTAL_ELAPSED_TIME / 60000 as DURATION_MINUTES,
    T.TOTAL_ELAPSED_TIME / 3600000 as DURATION_HOURS,
    T.ROWS_INSERTED,
    T.WAREHOUSE_NAME,
    T.USER_NAME
FROM TABLE(INFORMATION_SCHEMA.QUERY_HISTORY_BY_WAREHOUSE(
    WAREHOUSE_NAME => %(warehouse)s,
    END_TIME_RANGE_START => DATEADD(HOUR, -2, CURRENT_TIMESTAMP()),
    RESULT_LIMIT => 10000 
    )) T 
WHERE UPPER(T.QUERY_TEXT) LIKE 'CALL FINANCIERO.%%P_MAGIC_%%'
    AND T.EXECUTION_STATUS IN ('SUCCESS', 'FAILED', 'FAILED_WITH_ERROR', 'FAILED_WITH_INCIDENT', 'RUNNING', 'QUEUED')
    AND (T.TOTAL_ELAPSED_TIME > 10000 OR T.EXECUTION_STATUS IN ('RUNNING','QUEUED'))
ORDER BY T.START_TIME DESC